export const words = [
  {JP:"聖堂", EN:"shrine", type:"名"},
  {JP:"統治期間", EN:"reign", type:"名"},
  {JP:"最高傑作", EN:"masterpiece", type:"名"},
  {JP:"孤児", EN:"orphan", type:"名"},
  {JP:"礼儀", EN:"courtesy", type:"名"},
  {JP:"会合", EN:"gathering", type:"名"},
  {JP:"遠足", EN:"excursion", type:"名"},
  {JP:"茎", EN:"stalk", type:"名"},
  {JP:"大騒ぎ", EN:"fuss", type:"名"},
  {JP:"助言", EN:"counsel", type:"名"},
  {JP:"多数", EN:"multitude", type:"名"},
  {JP:"なぞなぞ", EN:"riddle", type:"名"},
  {JP:"軽蔑", EN:"scorn", type:"名"},
  {JP:"虚栄心", EN:"vanity", type:"名"},
  {JP:"さび", EN:"rust", type:"名"},
  {JP:"苦痛", EN:"torment", type:"名"},
]